workflows:
  my-workflow:
    scripts:
      - name: Build ipa for distribution
        script: xcode-project build-ipa --workspace "${ios}" --scheme "${ios}"
    artifacts:
      - build/ios/ipa/*.ipa
